name: Hello World
on:
  push:
    branches:
      -main
  pull_request:
    branches:
      -main
  issues:
    types: [opened]
  
  workflow_dispatch:
    inputs:
      name: 
        type: string
        description: Enter your name
        required: true

jobs:
  sayHello:
    runs-on: ubuntu-latest
    steps:
      - name: sayHello
        run: echo "Hello ${{ github.events.input.name }}"
        shell: bash
        
    
